# Generated by Django 3.0.6 on 2020-05-16 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('pay_type', models.PositiveSmallIntegerField(choices=[(0, 'Hourly'), (1, 'Salary')], default=0)),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=20)),
                ('employee', models.ManyToManyField(to='profit.Employee')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profit.JobType')),
            ],
        ),
    ]
