# Generated by Django 3.0.6 on 2020-05-16 04:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='clock_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 4, 19, 15, 615651, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='clock_out',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 4, 19, 21, 667943, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
