# Generated by Django 3.1 on 2020-10-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0007_auto_20200901_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
