# Generated by Django 3.1 on 2020-10-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0010_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='companies',
            field=models.ManyToManyField(to='profit.Company', verbose_name='Companies'),
        ),
    ]
